[package]
name = "find_returns"
version = "0.1.0"
authors = ["Logan King <seanloganking@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"stringr" = "0.1.1"
threadpool = "1.8.1"
num_cpus = "1.13.0"